# Generated by Django 5.2.8 on 2025-11-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_views', '0002_book_published_year_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
